# Generated by Django 4.2.1 on 2023-10-03 15:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
    ]
